FROM covlineages/pangolin:v4.3.1
RUN wget https://github.com/cov-lineages/pangolin-data/archive/refs/tags/v1.25.1.tar.gz && tar xzvf v1.25.1.tar.gz && \
    mv pangolin-data-1.25.1/pangolin_data/data/* /opt/conda/envs/pangolin/lib/python3.11/site-packages/pangolin_data/data/
