FROM covlineages/pangolin:v4.3.1
RUN wget https://github.com/cov-lineages/pangolin-data/archive/refs/heads/main.zip && unzip main.zip && \
    mv pangolin-data-main/pangolin_data/data/* /opt/conda/envs/pangolin/lib/python3.11/site-packages/pangolin_data/data/